### PR TITLE
google cloud service account and networks quotas 

### PR DESCRIPTION
**Pull request by jrluis**
Hi,

While using several kinds of dynamic slaves in google cloud (through labels) we found two problems:
- Bug: The Credential option, was single line. For using google cloud service accounts, it needs to be multiline, to allow the input of a private key.
  - The fix was to change in the jelly file to a multiline field
  - commit: ff81acf6e1ac12fc21f5dd8804d0fa3824c79539
- Bug: Networks weren't being configured when using the template option in jenkins ui. This made us hit the google cloud networks quota limit.
  - The fix was to pass to the template option the URI (as in the jclouds api example)
  - commit: 5f659921f295af105432b6235538ea0dc8915d87

Regards

### CODE REVIEW

**Comment by olivergondza** [comment]
Note https://github.com/jenkinsci/jclouds-plugin/pull/83 refactors the way credentials are handles as well.

**Comment by jrluis** [comment]
@olivergondza just refactored the code to introduce the minimal amount of changes to fix the bugs.

We are also aware of #83 and wish to use the same strategy for the credentials. 
The multiline field change is a just a quick fix until we get #83 merged.

**Comment by jrluis** [comment]
@olivergondza please don't merge yet, there is something fishy regarding jclouds version.

**Comment by jrluis** [comment]
It's ready to merge.

* Regarding -> Bug: The Credential option, was single line. For using google cloud service accounts, it needs to be multiline, to allow the input of a private key.
 * There is no change in this
* Regarding -> Bug: Networks weren't being configured when using the template option in jenkins ui. This made us hit the google cloud networks quota limit.
 * This was caused by bumping jclouds to 2.X-SNAPSHOT, the code was reverted.

We made a monkey patch 4dddb58ea97415d889d58855b5862711adf40806 because google cloud now allows creating images from rawdisk or sourcedisk. 
* See: https://cloud.google.com/compute/docs/reference/latest/images/insert 
* We use images created using sourcedisk (using packer)
* Without the monkey patch, the plugin doesn't work on projects with images created using sourcedisk (raises npe)
* In jclouds-labs-google master, this problem is allready fixed
** See: https://github.com/jclouds/jclouds-labs-google/blob/master/google-compute-engine/src/main/java/org/jclouds/googlecomputeengine/domain/Image.java
** The monkey patch should be removed when the jclouds-plugin upgrades to a 2.X release (it should bring the latest jcloud-labs-google)

Regards

**Comment by marcuspen** [comment]
Any idea when this will be merged? This bug with the credentials is a real blocker

**Comment by felfert** [comment]
Short answer: Not anytime soon.

Long version:
I am still not finished with the changes that #83 started. The global credentials still use simple text fields instead of a Credentials object. Also, the whole blobstore code has still to be converted. (I have a PR against my fork for that, but unfortunately it is not backward compatible - so that needs more work too). As soon as I have free time I will implement those.
After *that*, we can think about merging this.

Apart from that, I am not really happy about that "monkey" patch. Using an unreleased (2.x) version of jclouds is not a good idea IMHO.
@olivergondza Any opinion on this?

Does anyone know, when jclouds 2.0 is to be released?

Cheers
 -Fritz

**Comment by olivergondza** [comment]
Hi, first of all, I abandoned the use and contribution to this plugin in favor of https://github.com/jenkinsci/openstack-cloud-plugin, as that is all I need. Mainly because I do not see a way to responsibly maintain a plugin that tries to support so many cloud providers. Historically, there is simply not enough hands to verify new fixes from all that perspectives and no matter how hard is Apache JClouds trying, there are differences we need to pay attention to. Those differences either require countless `if (provider == X)` hacks and thay stretches the plugin to different directions that are quite hard to get compatible (which is sort of the case of this PR).

So while I can not comment on google cloud integration, dragging the class here temporarily is a practice used occasionally is plugins, nasty one though. Another option is build against 2.0 snapshot published by jclouds.

**Comment by felfert** [comment]
@jrluis and @marcuspen : 
I just realized, that the multiline issue might be solved using the existing credential. So:
Could you please confirm, thet the key is a standard PEM-encoded RSA or DSA key?
If yes, this could be implemented pretty soon
Or: Do you have an example key?

Thanks
 -Fritz

**Comment by felfert** [comment]
FYI.
Well, I signed up to google cloud service myself, just to see how these keys look. Unfortunately the are neither RSA nor DSA but a PEM-Encoded **unencrypted!**  PKCS#8. So this cannot be handled by the existing ssh-keys mechanisms but needs some more treatment in order to do it right.

**Comment by robertdolca** [comment]
@jrluis did you manage to make any version of the plugin work with Google Cloud Engine?

**Comment by jrluis** [comment]
@robertdolca Yes, it's working on gcloud using a build with this pull request.

**Comment by robertdolca** [comment]
I just compiled it but I get `Cannot connect to specified cloud, please check the identity and credentials: null`
I am using this as endpoint `https://www.googleapis.com/compute/v1/projects/<project-name>` the account's `client_email` as `identity` and for the `credential` I tried with the key from the json file and with the converted p12. Are you doing something different?

**Comment by jrluis** [comment]
@robertdolca Can you post a detailed stack trace?

**Comment by robertdolca** [comment]
In the meantime I figured it out. Jclouds asumes that the username is the same with the project name and the project name does not container '-'. It removes anything after - in the username and that is ther project name. Google does not follow this convention any more.

**Comment by felfert** [comment]
Now, that jclouds-2.0 was released last week, I added an Import feature for JSON keys and verified
overall operation. The workaround for the networks does not appear to be necessary anymore.
Therefore: closing this PR.

**Pull request closed without merging**
