### PR TITLE
[FIXED JENKINS-25865] Provision machines with NORMAL mode

### PR DESCRIPTION
**Pull request by olivergondza**
Fixes [JENKINS-25865](https://issues.jenkins-ci.org/browse/JENKINS-25865)

### CODE REVIEW

**Comment by felfert** [comment]
This **really** should be configurable!
Since I'm already working on some major changes in the config GUI (using ssh-credentials resp. credentials plugin wherever possible), I can take care of that.

**Comment by olivergondza** [comment]
What is the usecase for explicit configuration?

**Comment by felfert** [comment]
It means: Do not use this slaves for anything else but the speciefied labels.
In other words, it disables matching jobs **without** a Label-Expression to this slave.

**Comment by olivergondza** [comment]
Right, I have just realized it is explicitly configured for `DumbSlave`s as well. That would work for me. I prefer `NORMAL` mode to be the default, same as for `DumbSlave`.

**Comment by felfert** [comment]
If that's the case whith a none-empty label, then this would be a bug of
the generic job/executor mather (Perhaps you left the label empty? -
this is not validated in this plugin yet - of course it will be if I
touch the code).

NORMAL:
 - Label is optional.
EXPLICIT:
 - Label is mandatory - not shure what happens if slave label is empty.

Cheers
 -Fritz

**Comment by olivergondza** [comment]
Agree, I do not mind fixing this myself.

**Pull request closed without merging**
