### PR TITLE
Add ability to configure interval between checks to see if a node has ph...

### PR DESCRIPTION
**Pull request by jcmoore3**
...oned home.

### CODE REVIEW

**Comment by olivergondza** [comment]
Why this need to  be configurable?

**Comment by jcmoore3** [comment]
In my Jenkins environment with OpenStack, we are using Windows VMs and it takes a VM around 3-4 minutes to come online after the first-boot cloudbase-init process completes.  I would like to reduce the time Jenkins spends waiting for the node by having this value configurable.  This can reduce the time it takes a node to come online by 30 seconds.  For example, if a node is online and ready and phones home just after a check occurs, we have to wait an additional 30 seconds for the next phone home check to be performed.  I realize the gain can be trivial but if we are already waiting 3-4 minutes for a Windows VM, as compared to < 30 sec for most Linux VMs, having this timeout value configurable allows us to cut down on the wait time.

**Comment by olivergondza** [comment]
In that case I assume you use different values for `waitPhoneHomeTimeout` on those two types of images. It would make more sense to define this as `waitPhoneHomeTimeout/100` or similar. Right now, it is `waitPhoneHomeTimeout/30` compared to the default timeout value.

**Comment by jcmoore3** [comment]
So you would be in favor of making the interval at which the phone home check is performed proportional to the overall `waitPhoneHomeTimeout`?  This idea is intriguing but concerns me as in a very busy environment, it may take more than the nominal 3-4 minutes, maybe double, for a node to become available. (This happens sometimes with dozens of Windows VMs in various states of spawning, building, deleting, etc)  I would not want to lose the ability to retain an upper bound absolute worst-case limit of say 10 minutes for `waitPhoneHomeTimeout` in order to have a smaller phone home check interval.  My intent of making this value configurable is to have more fine grained control over both parameters individually based on the performance constraints of a specific cloud environment.

For me, `waitPhoneHomeTimeout` is an absolute worst case value that, if reached, means things have gone horribly wrong.  If this timeout is reached, we should kill the node and launch another as we can assume that this one will never become available.  I agree that different images would likely have different values for `waitPhoneHomeTimeout` but I would not want to base any other checks on this value, thus my desire to make the phone home check independently configurable.

**Comment by olivergondza** [comment]
> So you would be in favor of making the interval at which the phone home check is performed proportional to the overall  `waitPhoneHomeTimeout` ?

Yes, that is what I suggest.

I am concerned the config can get unnecessarily complicated. What are your timeouts and acceptable check intervals? There was no discussion behind current default so reducing it to some other hard-coded value might be acceptable for everyone.

**Comment by felfert** [comment]
IMHO, it would be best to use a wait()/notify() (or similar mechanism) instead of polling the flag in intervals. Actually, waitPhoneHomeTimeout indeed was intended as worst-case value just like @jcmoore3 assumed.
I resumed working on this plugin recently, so lets see what I can do about that. ;-)

**Comment by felfert** [comment]
Closing this in favor of PR #91

**Pull request closed without merging**
