### PR TITLE
[JENKINS-28815] Providing nodes by "Image name" always works as by "Image ID"

### PR DESCRIPTION
**Pull request by felfert**
Fixes JENKINS-28815 circumventing jcloud's default image caching.

### CODE REVIEW

**Comment by nacx** [comment]
The lifetime of the image cache is controlled by the [PROPERTY_SESSION_INTERVAL](http://jclouds.apache.org/reference/javadoc/1.9.x/org/jclouds/Constants.html#PROPERTY_SESSION_INTERVAL) property, which defaults to 1 minute.

Getting the list of images can be a very expensive operation in some providers (such as aws-ec2), so it does not seem like a good idea to always recreate the compute service by default. Also take into account that creating the context is expensive: it creates the Guice injector, resolves the dependency graph and executes all the injections, etc.

Could you try exposing the PROPERTY_SESSION_INTERVAL so users can configure it to tune the lifetime of the image cache, and see if this fixes the issue? If it works it should be preferred as it wouldn't affect users that benefit from the cache.

**Comment by felfert** [comment]
Hi,

I cannot confirm what you tell about PROPERTY_SESSION_INTERVAL's default. At least in my test setup (using jclouds-1.9.1 and OpenStack). There, it is definitely **much** more. Anyway, I think i found a better solution:

1. Use templateBuilder.imageNameMatches() to set up the template.
2. If .createNodesInGroup() throws a RunNodesException:
  * find out why and **if** it is something image-related,
    retry the whole setup once - but this time do a "manual" search like in my first fix.

This reduces the costly operation to an absolute minimum (done only, if it has failed already due to a missing image)

I hope, this is satisfying.

BTW:
Meanwhile I grepped thru jclouds-1.9.x source and found this in
apis/openstack-nova/src/main/java/org/jclouds/openstack/nova/v2_0/NovaApiMetadata.java:
properties.setProperty(PROPERTY_SESSION_INTERVAL, 30 * 60 + "");

I guess this is what you get if you assign misleading property names. The property should have been named something like "jclouds.imagecache.timeout" in the first place. As evidence above shows, even jclouds **own developers** get misled by its name. Furthermore, in my **very humble** opinion, the whole image cache thingy in jclouds is **seriously broken** and I see no reason whatsoever to burden the user with "fixing" the situation by doing timeout "adjustments". The compute service itself should do something like I have done (invalidating the cache if its content has proven outdated) - just multiple levels further down, where it has the chance to act more sensible than I can do.

Cheers
 -Fritz

**Comment by nacx** [comment]
Any approach that reduces the number of times a context is created and the calls to get the list of images is a better solution (IMO).

> I guess this is what one gets if one assigns misleading property names. The property should have been named something like "jclouds.imagecache.timeout" in the first place. As evidence above shows, even jclouds own developers get misled by its name.

Agree. It is not confusion, though, but the same property being used for several things: image cache invalidation, re-authentication when authentication tokens expire, etc. That property basically indicates when "stuff that has a limited lifetime" expires, and it can also make sense to have all stuff that needs to be refreshed under the same property and value. This said, given that the image cache has now enough entity, it makes a lot of sense to add a dedicated property to configure its lifetime.

> Furthermore, in my very humble opinion, the whole image cache thingy in jclouds is seriously broken and I see no reason whatsoever to burden the user with "fixing" the situation by doing timeout "adjustments". The compute service itself should do something like I have done (invalidating the cache if its content has proven outdated) - just multiple levels further down, where it has the chance to act more sensible than I can do.

Yes, it is a known issue: [JCLOUDS-512](https://issues.apache.org/jira/browse/JCLOUDS-512), but IMO it is not that critical: the common pattern in cloud providers is that images don't change frequently. Since the cloud provider apis don't notify you when the images change, jclouds uses the timeout to expire the cache. But listing images is an expensive operation (try listing the AWS images without filters), so the results are better cached. The other invalidation point *known to jclouds* is when users use the ImageExtension to create a new image from a node as mentioned in the issue, and will be taken into account when the issue is fixed.

Apart from the jclouds specific comments, if we introduce an explicit property to configure the lifetime of the cache, do you think it would be worth exposing that property, which should be meaningful enough, so users can configure that? If that is an option, this can be revisited once the change is in a jclouds release.

Thanks for sharing your thoughts @felfert! This kind of feedback in downstream projects is highly appreciated and really helps understanding the real issues people encounters when using jclouds.

**Comment by felfert** [comment]
I think it, is a good start to have an explicit property for the image cache. At least one does not have to worry about possible side effects. Regarding the common pattern in cloud providers (low image change frequency), I partly disagree.
First, one has to define the term "Image":
  * If it is some pre-fabricated boot-medium, then it changes infrequently indeed.
  * If however (like in OpenStack) it also is a bootable snapshot of some existing VM (created by "nova image-create <server> <imagename>") the pattern changes drastically.

In our jenkins environment we create these "Snapshot"-Images very frequently (actually after every test iteration). We have ~ 40-50 images changing constantly. (This are test target setups which are updated, snapshotted and then reused for various integration tests). I think the reporter of [JENKINS-28815] has a similar scenario.
Of course, in such a scenario one expects the compute service to immediately pick up newly created snapshots and any caching is undesired (even if it is costly).

With the above two extremes in mind (and knowing that jenkins is usable in both), it becomes clear that some adjustment of the cache expiry *ideally* would be **per template**, *not* by some *global* property.

Just my 2cent
 -Fritz

**Comment by nacx** [comment]
Currently the TemplateBuilder falbacks to calling the cloud provider if the `imageId` is provided. We could fallback to *list* & filter (the expensive operation we try to avoid) if any other image property is provided and the builder has been instructed to do so.  WDYT about addind the following method to the TemplateBuilder?
```java
.cacheImages(false)
```
Dows it look like a cleaner solution rather than using properties to tune the cache itself (current properties will still apply)?

**Comment by felfert** [comment]
Yes! That would be perfect.

**Pull request merged**
