### PR TITLE
Added phone-home feature

### PR DESCRIPTION
**Pull request by felfert**
Hi guys,

This pull request adds a WebHook for handling phone-home POST request made by cloud-init.
Having those, you now can optionally wait for a slave to phone home, *before* attempting to connect via SSH.
This solves a lot of timing-related problems with VM provisioning.

### CODE REVIEW

**Comment by mavlyutov** [comment]
could you please describe use-cases of that feature in details? 
what erros/situations do you want to avoid? 
how do you want to use these phones home?

**Comment by felfert** [comment]
The use-cases are pretty easy and obvious (at least to me and for those who know cloud-init). Here are some examples where normal approach of retrying a SSH-connection can fail:

- Jenkins connects at a time when ssh is up and running but the keys or users to be used are not yet provisioned on the slave.
- The "Use preinstalled JDK" flag is enabled and jenkins connects at a time where the JDK is not yet provisioned on the slave. It scp's the slave.jar, but starting it fails.

For example, In our environment, provisioning can take up to 15 minutes until everything is ready to use on the slave. This is where coud-init (our main provisioning tool - a de-facto standard, available  on many pre-configured cloud images) can help:

After provisioning is finished on the slave, cloud init can issue a POST request back to jenkins, signalling it that the slave is now ready to be used.

The pull request implements 2 parts:
- A webHook (a special URL-path on jenkins) which is used as destination of the slave's phone-home POST. It listens for requests at https?://our-jenkins.url/jclouds-phonehome/ The implementation is based on code from kohsuke's github-plugin.

- A boolean flag+timeout value configurable in the SlaveTemplate which - when enabled - block the initial SSH connection attempt until the above mentioned POST request has been received from the slave (or a timeout happens or a delete is requested).

The usual configuration is two-fold (e.g. with OpenStack):
1. Activate the checkbox "Wait for slave to phone home"
2. In user-data, among other things specify something like this:
```
#cloud-config
phone_home:
  url: http://your.jenkins.url/jclouds-phonehome/
```

**Comment by mavlyutov** [comment]
ah, I see. two questions:
1. have you tested it on windows? if no, let's write smthg in help-message
2. is it a good idea to extend user-script automatically by checking new checkbox "Wait for slave to phone home"?

**Comment by felfert** [comment]
> 1. have you tested it on windows? if no, let's write smthg in help-message

No. Which part anyway? The jenkins-side part should work without any problems because it is just a url-path-interceptor. For the slave-side: cloudbase-init does not (yet) have a phone_home function but one could use curl or wget or write a plugin for cloudbase-init. If it's ready, I can write some tutorial and we can put a link to that into the help message.

> 2. is it a good idea to extend user-script automatically by checking new checkbox "Wait for slave to phone home"?

No. There are too many different ways to achieve this and I do not want to mess with the user-data. AFAIK, Some cloud providers do not even have user-data to begin with. Those would need to use init-scripts and curl or wget.

**Comment by felfert** [comment]
PS- I'm going to close this PR and create a PR against
https://github.com/mavlyutov/jclouds-plugin with both our merged code...

**BUT**: Your code is using  hudson.plugins.sshslaves.SSHLauncher the **wrong** way and thus **breaks** key-based authentication. (Tested here with Linux and OpenStack - using a pre-exising jenkins-user on the slave side). I have some ideas how this can be made to work. More via email...

**Pull request closed without merging**
